[package]
name = "SOApresentar"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = "0.61.1"

[windows]
features = [
    "Data_Xml_Dom",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Pipes",
    "Win32_UI_WindowsAndMessaging",
]
